### ISSUE TITLE
Auth0 React SDK?

### ISSUE THREAD

**Issue by jplock** [craigphares/gatsby-auth0#1]
Thank you so much for this repository! It was a big help in figuring out how to integrate Auth0 with Gatsby.  What do you think about https://auth0.com/docs/libraries/auth0-react? Would that simplify the integration?

**Comment by craigphares** [comment]
@jplock According to the Auth0 team, `auth0-react` is supposed to make things easier: https://community.auth0.com/t/securing-gatsby-with-auth0/24389

One of the big hurdles I encountered was keeping the user signed in with silent authentication, and according to comments on that post, it may still be an issue. But I imagine that library will be the way to go for securing Gatsby in the future.

**Comment by jplock** [comment]
I just found https://github.com/auth0/auth0-react/tree/master/examples/gatsby-app, and am going to give that a try, thanks again!
